"""Re-run the StatStream arm of the m=500 tables with the fixed tuning grid (2026-09-23, user).

The other session found that the CSZ tuner could not reach StatStream's lossless reporting size:
`statstream_bw_coeffs` was capped at b/2, which drops the Nyquist term of the basic window, so on
data whose spectrum is not concentrated at the bottom the arm missed nearly every true pair
(recall 0.000 on every differenced cell of the tables, 0.09 to 0.70 on raw). The grid now reaches
b/2+1. The library is untouched, so only StatStream's parameters change and only its rows need
redoing.

Per cell, two jobs: the CSZ tuning restricted to statstream, then an N-way run of bruteforce and
statstream only. Brute force is rerun because it is both the ground truth and the timing anchor
of the cell, so recall, precision and speedup stay defined exactly as in the tables (same job,
same node). CorrTrack's hyperopt is not rerun: the run reuses the existing HYPEROPT_DIR, which
only satisfies the wrapper's check since the corrtrack arm is not in ARMS.

Results land under <results-root>/{tuned,nway}/<stem>, separate from the full campaign, and the
table builder takes StatStream from here and every other arm from the original run.

    python abaca/campaign_statstream_rerun.py --emit abaca/statstream_rerun_submit.sh
    SNAPSHOT=... python abaca/campaign_feeder.py abaca/statstream_rerun_submit.sh
"""
from __future__ import annotations

import argparse
import os

import campaign_competitors as cc
import campaign_m500_tables as m500

OLD_ROOT = "$HOME/corrtrack_abaca_results"          # the full campaign's hyperopt and nway results
UNTUNABLE = {"smartmeter_m500_m500_W48_s8_L0_T0.95_diff_pos"}   # no correlated pair in the calibration span


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--emit", required=True)
    ap.add_argument("--results-root", default="$HOME/corrtrack_abaca_results/statstream_fix")
    args = ap.parse_args()

    lines = ["#!/bin/bash", "# generated by abaca/campaign_statstream_rerun.py: StatStream only, fixed tuning grid",
             "set -uo pipefail", f"RESULTS_ROOT=${{RESULTS_ROOT:-{args.results_root}}}",
             "SNAPSHOT=${SNAPSHOT:?set SNAPSHOT to a tree carrying the fixed abaca/tune_competitors.py}",
             "[ -f \"$SNAPSHOT/SNAPSHOT_OK\" ] || { echo \"no SNAPSHOT_OK in $SNAPSHOT\" >&2; exit 4; }",
             "mkdir -p abaca/logs",
             # no host subsets: pinning the packed jobs to four hosts deadlocked the campaign of 2026-09-22
             # when other users held them; the cluster pin keeps every cell on identical hardware
             "submit() { oarsub -q abaca -p \"cluster='mercantour3'\" \"$@\" | sed -n 's/^OAR_JOB_ID=//p'; }", ""]
    n = 0
    for c in m500.m500_cells():
        for tag, neg in (("pos", ""), ("neg", "NEG_CORR_FLAG=--neg-corr")):
            stem = f"{c.stem}_{tag}"
            sync = "_L0_" in c.stem
            want = (sync and tag == "pos") or (not sync)          # table S is pos only; L and N are the lagged runs
            if not want or stem in UNTUNABLE:
                continue
            common = [f"DATASET_CONFIG={c.config}", f"WINDOW_SIZE={c.W}", f"WINDOW_STEP={c.step}", f"BASIC_WINDOW={c.step}",
                      f"N_LAGS={c.n_lags}", f"THR={c.T}", f"PREPROCESS={1 if c.preprocess else 0}", "SNAPSHOT=$SNAPSHOT",
                      "EXTRA_ARGS=" + c.extra_args().replace(" ", "+")] + ([neg] if neg else [])
            tuned = f"$RESULTS_ROOT/tuned/{stem}"
            t_cmd = " ".join(["$SNAPSHOT/abaca/tune_competitors.oar"] + common + ["ARMS=statstream", f"CALIB_OBS={c.calib_obs}",
                             f"CALIB_WINDOWS={cc.CALIB_WINDOWS}", f"CALIB_SERIES={cc.CALIB_SERIES}", f"OUT_DIR={tuned}"])
            n_cmd = " ".join(["$SNAPSHOT/abaca/nway_compare.oar"] + common +
                             ["ARMS=bruteforce,statstream", f"COMPETITOR_PARAMS={tuned}",
                              f"HYPEROPT_DIR={OLD_ROOT}/hyperopt/{stem}", "NWAY_LARGE_SET_GB=200", "EVAL_SPAN=full",
                              f"RUN_NAME={stem}"])
            lines += [f"# --- {stem}: StatStream rerun with the fixed bw_coeffs grid",
                      f"T_JOB=$(submit -n ts_{stem} -l core=2,walltime=6:00:00 -S \"{t_cmd}\")",
                      f"N_JOB=$(submit -n ns_{stem} -a \"$T_JOB\" -l host=1,walltime=6:00:00 -S \"{n_cmd}\")",
                      f"echo \"{stem} T=$T_JOB N=$N_JOB\"", ""]
            n += 1
    open(args.emit, "w").write("\n".join(lines) + "\n")
    os.chmod(args.emit, 0o755)
    print(f"{n} cells x 2 jobs = {2 * n} jobs -> {args.emit}")


if __name__ == "__main__":
    main()
