"""Update three arms of the m=500 tables against the 2026-09-23 code (user).

Three changes from the other session need new measurements, and only for the arms they touch:
  statstream  the CSZ tuner could not reach the lossless reporting size (bw_coeffs was capped at
              b/2, dropping the Nyquist term), so the arm missed nearly every true pair. All
              classes are affected.
  corrjoin    now runs lagged (its filters are time-agnostic), so it enters class L. It still has
              no negative correlation, so it stays out of class N.
  tsubasa     now runs lagged (Lemma 1 holds between segments shifted by whole basic windows), so
              it enters classes L and N.
Both lagged arms carry supports_lags="enabled_by_us" in their rows: the capability is ours, not
their authors'. The rest of the table keeps its original measurements; the rename of exact_stomp
to bf_incremental is backwards compatible and the other hunks are disclosure plumbing, which a
separate three-cell A/B check confirms rather than assumes.

The other session found that the CSZ tuner could not reach StatStream's lossless reporting size:
`statstream_bw_coeffs` was capped at b/2, which drops the Nyquist term of the basic window, so on
data whose spectrum is not concentrated at the bottom the arm missed nearly every true pair
(recall 0.000 on every differenced cell of the tables, 0.09 to 0.70 on raw). The grid now reaches
b/2+1. The library is untouched, so only StatStream's parameters change and only its rows need
redoing.

Per cell, two jobs: the CSZ tuning restricted to the arms that need it, then an N-way run of
bruteforce and the arms being updated (class S: statstream; class L: statstream, corrjoin,
tsubasa; class N: statstream, tsubasa). Brute force is rerun because it is both the ground truth and the timing anchor
of the cell, so recall, precision and speedup stay defined exactly as in the tables (same job,
same node). CorrTrack's hyperopt is not rerun: the run reuses the existing HYPEROPT_DIR, which
only satisfies the wrapper's check since the corrtrack arm is not in ARMS.

Results land under <results-root>/{tuned,nway}/<stem>, separate from the full campaign, and the
table builder takes StatStream from here and every other arm from the original run.

    python abaca/campaign_arm_updates.py --emit abaca/statstream_rerun_submit.sh
    SNAPSHOT=... python abaca/campaign_feeder.py abaca/statstream_rerun_submit.sh
"""
from __future__ import annotations

import argparse
import os

import campaign_competitors as cc
import campaign_m500_tables as m500

OLD_ROOT = "$HOME/corrtrack_abaca_results"          # the full campaign's hyperopt and nway results
UNTUNABLE = {"smartmeter_m500_m500_W48_s8_L0_T0.95_diff_pos"}   # no correlated pair in the calibration span


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--emit", required=True)
    ap.add_argument("--results-root", default="$HOME/corrtrack_abaca_results/arm_updates")
    args = ap.parse_args()

    lines = ["#!/bin/bash", "# generated by abaca/campaign_arm_updates.py: StatStream only, fixed tuning grid",
             "set -uo pipefail", f"RESULTS_ROOT=${{RESULTS_ROOT:-{args.results_root}}}",
             "SNAPSHOT=${SNAPSHOT:?set SNAPSHOT to the 2026-09-23 tree (fixed tuner + lagged corrjoin/tsubasa)}",
             "[ -f \"$SNAPSHOT/SNAPSHOT_OK\" ] || { echo \"no SNAPSHOT_OK in $SNAPSHOT\" >&2; exit 4; }",
             "mkdir -p abaca/logs",
             # no host subsets: pinning the packed jobs to four hosts deadlocked the campaign of 2026-09-22
             # when other users held them; the cluster pin keeps every cell on identical hardware
             "submit() { oarsub -q abaca -p \"cluster='mercantour3'\" \"$@\" | sed -n 's/^OAR_JOB_ID=//p'; }", ""]
    n = 0
    for c in m500.m500_cells():
        for tag, neg in (("pos", ""), ("neg", "NEG_CORR_FLAG=--neg-corr")):
            stem = f"{c.stem}_{tag}"
            sync = "_L0_" in c.stem
            want = (sync and tag == "pos") or (not sync)          # table S is pos only; L and N are the lagged runs
            if not want or stem in UNTUNABLE:
                continue
            common = [f"DATASET_CONFIG={c.config}", f"WINDOW_SIZE={c.W}", f"WINDOW_STEP={c.step}", f"BASIC_WINDOW={c.step}",
                      f"N_LAGS={c.n_lags}", f"THR={c.T}", f"PREPROCESS={1 if c.preprocess else 0}", "SNAPSHOT=$SNAPSHOT",
                      "EXTRA_ARGS=" + c.extra_args().replace(" ", "+")] + ([neg] if neg else [])
            tuned = f"$RESULTS_ROOT/tuned/{stem}"
            arms = ["statstream"] + (["corrjoin", "tsubasa"] if (not sync and tag == "pos") else (["tsubasa"] if not sync else []))
            tune_arms = [a for a in arms if a in ("statstream", "corrjoin")]        # tsubasa is exact and has no knobs
            t_cmd = " ".join(["$SNAPSHOT/abaca/tune_competitors.oar"] + common + [f"ARMS={','.join(tune_arms)}", f"CALIB_OBS={c.calib_obs}",
                             f"CALIB_WINDOWS={cc.CALIB_WINDOWS}", f"CALIB_SERIES={cc.CALIB_SERIES}", f"OUT_DIR={tuned}"])
            n_cmd = " ".join(["$SNAPSHOT/abaca/nway_compare.oar"] + common +
                             [f"ARMS={','.join(['bruteforce'] + arms)}", f"COMPETITOR_PARAMS={tuned}",
                              f"HYPEROPT_DIR={OLD_ROOT}/hyperopt/{stem}", "NWAY_LARGE_SET_GB=200", "EVAL_SPAN=full",
                              f"RUN_NAME={stem}"])
            lines += [f"# --- {stem}: arm updates ({','.join(arms)})",
                      f"T_JOB=$(submit -n ts_{stem} -l core=2,walltime=6:00:00 -S \"{t_cmd}\")",
                      f"N_JOB=$(submit -n ns_{stem} -a \"$T_JOB\" -l host=1,walltime=6:00:00 -S \"{n_cmd}\")",
                      f"echo \"{stem} T=$T_JOB N=$N_JOB\"", ""]
            n += 1
    open(args.emit, "w").write("\n".join(lines) + "\n")
    os.chmod(args.emit, 0o755)
    print(f"{n} cells x 2 jobs = {2 * n} jobs -> {args.emit}")


if __name__ == "__main__":
    main()
