"""Update three arms of the m=500 tables against the 2026-09-23 code (user).

Three changes from the other session need new measurements, and only for the arms they touch:
  statstream  the CSZ tuner could not reach the lossless reporting size (bw_coeffs was capped at
              b/2, dropping the Nyquist term), so the arm missed nearly every true pair. All
              classes are affected.
  corrjoin    now runs lagged (its filters are time-agnostic), so it enters class L. It still has
              no negative correlation, so it stays out of class N.
  tsubasa     now runs lagged (Lemma 1 holds between segments shifted by whole basic windows), so
              it enters classes L and N.
Both lagged arms carry supports_lags="enabled_by_us" in their rows: the capability is ours, not
their authors'. The rest of the table keeps its original measurements; the rename of exact_stomp
to bf_incremental is backwards compatible and the other hunks are disclosure plumbing, which a
separate three-cell A/B check confirms rather than assumes.

The other session found that the CSZ tuner could not reach StatStream's lossless reporting size:
`statstream_bw_coeffs` was capped at b/2, which drops the Nyquist term of the basic window, so on
data whose spectrum is not concentrated at the bottom the arm missed nearly every true pair
(recall 0.000 on every differenced cell of the tables, 0.09 to 0.70 on raw). The grid now reaches
b/2+1. The library is untouched, so only StatStream's parameters change and only its rows need
redoing.

Per cell, two jobs: the CSZ tuning restricted to the arms that need it, then an N-way run of
bruteforce and the arms being updated (class S: statstream; class L: statstream, corrjoin,
tsubasa; class N: statstream, tsubasa). Brute force is rerun because it is both the ground truth and the timing anchor
of the cell, so recall, precision and speedup stay defined exactly as in the tables (same job,
same node). CorrTrack's hyperopt is not rerun: the run reuses the existing HYPEROPT_DIR, which
only satisfies the wrapper's check since the corrtrack arm is not in ARMS.

Results land under <results-root>/{tuned,nway}/<stem>, separate from the full campaign, and the
table builder takes StatStream from here and every other arm from the original run.

    python abaca/campaign_arm_updates.py --emit abaca/statstream_rerun_submit.sh
    SNAPSHOT=... python abaca/campaign_feeder.py abaca/statstream_rerun_submit.sh
"""
from __future__ import annotations

import argparse
import os

import campaign_competitors as cc
import campaign_m500_tables as m500

OLD_ROOT = "$HOME/corrtrack_abaca_results"          # the full campaign's hyperopt and nway results
UNTUNABLE = {"smartmeter_m500_m500_W48_s8_L0_T0.95_diff_pos"}   # no correlated pair in the calibration span
TUNE_CORES = os.environ.get("TUNE_CORES", "2")   # 2026-09-24: the dense lagged cells killed a 2-core
                                                # tuning job at 19.6 GB (about 9.6 GB per core here)
FULL_ARMS = os.environ.get("FULL_ARMS", "1") != "0"
OPTIMIZED_ARMS = os.environ.get("OPTIMIZED_ARMS", "0") != "0"   # only the arms that share the candidate stage    # rerun every arm (repair mode), not only the updated ones
ONLY_CELLS = set(l.strip() for l in open(os.environ["ONLY_CELLS"]) if l.strip()) if os.environ.get("ONLY_CELLS") else None


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--emit", required=True)
    ap.add_argument("--results-root", default="$HOME/corrtrack_abaca_results/arm_updates")
    args = ap.parse_args()

    lines = ["#!/bin/bash", "# generated by abaca/campaign_arm_updates.py: StatStream only, fixed tuning grid",
             "set -uo pipefail", f"RESULTS_ROOT=${{RESULTS_ROOT:-{args.results_root}}}",
             "SNAPSHOT=${SNAPSHOT:?set SNAPSHOT to the 2026-09-23 tree (fixed tuner + lagged corrjoin/tsubasa)}",
             "[ -f \"$SNAPSHOT/SNAPSHOT_OK\" ] || { echo \"no SNAPSHOT_OK in $SNAPSHOT\" >&2; exit 4; }",
             "mkdir -p abaca/logs",
             # no host subsets: pinning the packed jobs to four hosts deadlocked the campaign of 2026-09-22
             # when other users held them; the cluster pin keeps every cell on identical hardware
             "submit() { oarsub -q abaca -p \"cluster='mercantour3'\" \"$@\" | sed -n 's/^OAR_JOB_ID=//p'; }", ""]
    n = 0
    for c in m500.m500_cells():
        for tag, neg in (("pos", ""), ("neg", "NEG_CORR_FLAG=--neg-corr")):
            stem = f"{c.stem}_{tag}"
            sync = "_L0_" in c.stem
            want = (sync and tag == "pos") or (not sync)          # table S is pos only; L and N are the lagged runs
            if not want or stem in UNTUNABLE or (ONLY_CELLS is not None and stem not in ONLY_CELLS):
                continue
            # RESULTS_ROOT must travel as a job parameter: nway_compare.oar and tune_competitors.oar
            # build their output directory from the RESULTS_ROOT *inside the job*, and the default is
            # $HOME/corrtrack_abaca_results, i.e. the campaign's own nway/<cell> (2026-09-23: omitting it
            # overwrote 120 cells of full-arm results with 2-to-4-arm ones)
            common = [f"DATASET_CONFIG={c.config}", f"WINDOW_SIZE={c.W}", f"WINDOW_STEP={c.step}", f"BASIC_WINDOW={c.step}",
                      f"N_LAGS={c.n_lags}", f"THR={c.T}", f"PREPROCESS={1 if c.preprocess else 0}", "SNAPSHOT=$SNAPSHOT",
                      "RESULTS_ROOT=$RESULTS_ROOT",
                      "EXTRA_ARGS=" + c.extra_args().replace(" ", "+")] + ([neg] if neg else [])
            tuned = f"$RESULTS_ROOT/tuned/{stem}"
            if OPTIMIZED_ARMS:
                # (2026-09-24, user) the candidate stage (Sketches / Candidates) was optimised, which changes
                # the timing of every arm that goes through it: the four tuned competitors and both CorrTrack
                # backends. The five arms built on Candidates_BF_* (bf_incremental, filcorr, tsubasa, braid,
                # thinbraid) do not use it and keep their measurements; bruteforce reruns as truth and anchor.
                arms = ["parcorr", "csz", "statstream", "corrjoin", "corrtrack", "corrtrack_hamming"]
                if tag == "neg":
                    arms = [a for a in arms if a not in ("parcorr", "csz", "corrjoin")]   # no negative correlation
                tune_arms = [a for a in arms if a in ("parcorr", "csz", "statstream", "corrjoin")]
            elif FULL_ARMS:
                # (2026-09-23, user) rerun the whole arm set on the new code, which also puts every arm of
                # these cells on one code state and makes the A/B comparison unnecessary for them
                arms = ["all"]
                tune_arms = ["parcorr", "csz", "statstream"] + (["corrjoin"] if tag == "pos" else [])
            else:
                arms = ["statstream"] + (["corrjoin", "tsubasa"] if (not sync and tag == "pos") else (["tsubasa"] if not sync else []))
                tune_arms = [a for a in arms if a in ("statstream", "corrjoin")]    # tsubasa is exact and has no knobs
            # (2026-09-24) CorrTrack is re-tuned under the code being measured, like the competitors: the
            # candidate-stage optimisation made an index insert about five times cheaper, so parameters fitted
            # under the old cost model are valid but no longer speed-optimal, and reusing them would handicap
            # the one arm whose own procedure is supposed to choose them.
            hyper = f"$RESULTS_ROOT/hyperopt/{stem}"
            hyper_h = f"$RESULTS_ROOT/hyperopt_hamming/{stem}"
            h_cmd = " ".join(["$SNAPSHOT/abaca/hyperopt_corrtrack.oar"] + common + [f"OUT_DIR={hyper}"])
            h2_cmd = " ".join(["$SNAPSHOT/abaca/hyperopt_corrtrack.oar"] + common +
                              ["PARAM_GRID_CONFIG=experiment_run_param_grid_campaign_hamming.py", f"OUT_DIR={hyper_h}"])
            t_cmd = " ".join(["$SNAPSHOT/abaca/tune_competitors.oar"] + common + [f"ARMS={','.join(tune_arms)}", f"CALIB_OBS={c.calib_obs}",
                             f"CALIB_WINDOWS={cc.CALIB_WINDOWS}", f"CALIB_SERIES={cc.CALIB_SERIES}", f"OUT_DIR={tuned}"])
            n_cmd = " ".join(["$SNAPSHOT/abaca/nway_compare.oar"] + common +
                             [f"ARMS={'all' if (FULL_ARMS and not OPTIMIZED_ARMS) else ','.join(['bruteforce'] + arms)}", f"COMPETITOR_PARAMS={tuned}",
                              f"HYPEROPT_DIR={hyper}", f"HYPEROPT_HAMMING_DIR={hyper_h}",
                              "NWAY_LARGE_SET_GB=200", "EVAL_SPAN=full",
                              f"RUN_NAME={stem}"])
            lines += [f"# --- {stem}: arm updates ({','.join(arms)})",
                      f"H_JOB=$(submit -n hs_{stem} -l core={TUNE_CORES},walltime=6:00:00 -S \"{h_cmd}\")",
                      f"H2_JOB=$(submit -n hh_{stem} -l core={TUNE_CORES},walltime=6:00:00 -S \"{h2_cmd}\")",
                      f"T_JOB=$(submit -n ts_{stem} -l core={TUNE_CORES},walltime=6:00:00 -S \"{t_cmd}\")",
                      f"N_JOB=$(submit -n ns_{stem} -a \"$H_JOB\" -a \"$H2_JOB\" -a \"$T_JOB\" -l host=1,walltime=6:00:00 -S \"{n_cmd}\")",
                      f"echo \"{stem} H=$H_JOB H2=$H2_JOB T=$T_JOB N=$N_JOB\"", ""]
            n += 1
    open(args.emit, "w").write("\n".join(lines) + "\n")
    os.chmod(args.emit, 0o755)
    print(f"{n} cells x 2 jobs = {2 * n} jobs -> {args.emit}")


if __name__ == "__main__":
    main()
